spring.application.name=finditdit
# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/finditdit
spring.datasource.username=postgres
spring.datasource.password=12345678
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# App
server.port=8080
spring.application.name=FindIt DIT